#
#   This file copied from zilla-dist-pm/pkg/travis.yml
#

language: perl

perl:
- '5.20'
- '5.18'
- '5.16'
- '5.14'
- '5.12'
- '5.10'
# - '5.8'

install:
- cpanm --quiet --notest
  Devel::Cover::Report::Coveralls
  ExtUtils::MakeMaker
  File::Share
  Hash::Merge
  IO::All
  Swim
  Swim::Plugin::badge
  Template::Toolkit::Simple
  version
  YAML::XS

#   CPAN::Uploader
#   Dist::Zilla
#   Dist::Zilla::Plugin::ChangesFromYaml
#   Dist::Zilla::Plugin::GithubMeta
#   Dist::Zilla::Plugin::ReadmeFromPod
#   Dist::Zilla::Plugin::TestBaseIncluder
#   Dist::Zilla::Plugin::TestMLIncluder
#   Dist::Zilla::PluginBundle::Git

script:
- :; [ ! -e test ] ||
  PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine
  prove -lv test/
- :; [ ! -e test ] || cover

after_success:
- cover -report coveralls

notifications:
  irc:
    channels:
    - irc.freenode.net#pkg
    on_success: change
    on_failure: always
    skip_join: true

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
